<?php

/*
 * Builder constant
 * 
 * Initlize V0.0.10         20170210        Joe
 * 
 */

$_CONSTANT_DEFAULT_TARGET_URL = 'http://127.0.0.1:5000';

$_CONSTANT_TIMESTAMP_TEST_FLG = 'Z_TEST_TIMESTAMP';

$_CONSTANT_MSG_NO_POST_DATA = 'No post data to builder!!';

$_CONSTANT_ERR_CODE_EXCEPTION_POST_DATA = 'err_build_001';
$_CONSTANT_ERR_CODE_NO_TARGET_URL = 'err_build_002';
$_CONSTANT_ERR_CODE_CURL_POST_EXCEPTION = 'err_build_003';
$_CONSTANT_ERR_CODE_ILLEGAL_URL = 'err_build_999';

$_CONSTANT_WRN_CODE_CANT_PUSH_PATH = 'wrn_build_001';
$_CONSTANT_WRN_CODE_ILLEGAL_FROM_PATH = 'wrn_build_002';
$_CONSTANT_WRN_CODE_NO_FROM_DATA = 'wrn_build_003';

$_CONSTANT_NOTE_CODE_NO_HEAD = 'note_build_001';
$_CONSTANT_NOTE_CODE_NO_MODEL_FLG = 'note_build_002';
$_CONSTANT_NOTE_CODE_NO_MODEL_FLG_DATA = 'note_build_003';
