<?php
/*
 * Route constant
 * 
 * Initlize V0.0.10         20170210        Joe
 * 
 */

$_CONSTANT_ROUTE_SELECT_TARGET = 'builderType';
$_CONSTANT_DEFAULT_TARGET_URL = 'http://127.0.0.1:5000';

$_CONSTANT_TIMESTAMP_TEST_FLG = 'Z_TEST_TIMESTAMP';

$_CONSTANT_MSG_NO_POST_DATA = 'No post data to router!!';

$_CONSTANT_ERR_CODE_EXCEPTION_POST_DATA = 'err_route_001';
$_CONSTANT_ERR_CODE_NO_HEAD = 'err_route_002';
$_CONSTANT_ERR_CODE_NO_ROUTE_FLG = 'err_route_003';
$_CONSTANT_ERR_CODE_NO_ROUTE_FLG_DATA = 'err_route_004';
$_CONSTANT_ERR_CODE_NO_TARGET_URL = 'err_route_005';
$_CONSTANT_ERR_CODE_CURL_POST_EXCEPTION = 'err_route_006';
$_CONSTANT_ERR_CODE_ILLEGAL_URL = 'err_route_999';

$_CONSTANT_WRN_CODE_CANT_PUSH_PATH = 'wrn_route_001';
$_CONSTANT_WRN_CODE_ILLEGAL_FROM_PATH = 'wrn_route_002';
$_CONSTANT_WRN_CODE_NO_FROM_DATA = 'wrn_route_003';

